---
- hosts: 127.0.0.1
  user: root
  vars:
    default_locale: fr_FR.UTF-8
  tasks:
  - apt: pkg=locales state=latest
  - apt: pkg=language-pack-fr state=latest
  - copy: dest=/etc/locale.gen content="{{default_locale}} UTF-8" mode=0644
    register: locale_gen
  - name: write /etc/default/locale
    action: template src=templates/locale dest=/etc/default/locale mode=0644
    register: locale
  - command: /usr/sbin/locale-gen
    when: locale_gen.changed or locale.changed
  - command: /usr/sbin/update-locale
    when: locale_gen.changed or locale.changed